# Generated by Django 4.2.1 on 2024-10-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=50)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('g2', models.BooleanField(default=False)),
                ('g3', models.BooleanField(default=False)),
                ('g4', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Network Coverages',
            },
        ),
    ]
